import { PatientRecord } from './types';

export const INITIAL_RECORDS: PatientRecord[] = [
  {
    id: 'seed-1',
    date: '2026-03-24',
    ptNo: 'PT69-001',
    serviceType: 'new',
    citizenId: '3-4305-00355-60-9',
    name: 'นายจักรกริช ราชสิงห์',
    gender: 'male',
    birthYear: '2504',
    age: '65',
    address: '118 ม.6 ต.เดชอุดม อ.เดชอุดม จ.อุบลราชธานี',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดไหล่',
    ptDiagnosis: 'Frozen Shoulder',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-03-24T09:00:00Z').toISOString()
  },
  {
    id: 'seed-2',
    date: '2026-03-28',
    ptNo: 'PT69-002',
    serviceType: 'followup',
    citizenId: '',
    name: 'นางดารารัตน์ รัตนโคตร',
    gender: 'female',
    birthYear: '2508',
    age: '61',
    address: 'ต.เดชอุดม อ.เดชอุดม จ.อุบลราชธานี',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดหลัง',
    ptDiagnosis: 'LBP',
    treatments: ['PMS'],
    otherTreatment: '',
    fee: 450,
    remarks: '',
    createdAt: new Date('2026-03-28T10:30:00Z').toISOString()
  },
  {
    id: 'seed-3',
    date: '2026-04-04',
    ptNo: 'PT69-003',
    serviceType: 'new',
    citizenId: '',
    name: 'นายเจริญ พฤกษาสน',
    gender: 'male',
    birthYear: '2529',
    age: '40',
    address: '',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดบ่า',
    ptDiagnosis: 'MPS',
    treatments: ['PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-04-04T08:15:00Z').toISOString()
  },
  {
    id: 'seed-4',
    date: '2026-04-05',
    ptNo: 'PT69-004',
    serviceType: 'new',
    citizenId: '',
    name: 'นางสาวศิริลักษณ์ ดวงจันทร์',
    gender: 'female',
    birthYear: '2512',
    age: '57',
    address: '',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดสะโพก',
    ptDiagnosis: 'LBP',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-04-05T14:20:00Z').toISOString()
  },
  {
    id: 'seed-5',
    date: '2026-04-06',
    ptNo: 'PT69-005',
    serviceType: 'followup',
    citizenId: '1-3409-00001-71-9',
    name: 'น.ส. อังคณา จำปาทอง',
    gender: 'female',
    birthYear: '2549',
    age: '20',
    address: '400 ม.4 ต.โพธิ์ อ.เมือง จ.ศรีสะเกษ',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดคอ',
    ptDiagnosis: 'C-Spondylosis',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 800,
    remarks: '',
    createdAt: new Date('2026-04-06T09:00:00Z').toISOString()
  },
  {
    id: 'seed-6',
    date: '2026-04-06',
    ptNo: 'PT69-006',
    serviceType: 'new',
    citizenId: '1-3407-00315-76-0',
    name: 'นายวีรภัทร ชินช้าง',
    gender: 'male',
    birthYear: '2533',
    age: '36',
    address: '148 ม.6 ต.สำโรง อ.สำโรง จ.อุบลราชธานี',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดต้นคอ ร้าวบ่า',
    ptDiagnosis: 'C-Spondylosis',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-04-06T11:00:00Z').toISOString()
  },
  {
    id: 'seed-7',
    date: '2026-04-07',
    ptNo: 'PT69-007',
    serviceType: 'new',
    citizenId: '',
    name: 'นายธนชัย โคตรสาร',
    gender: 'male',
    birthYear: '2502',
    age: '67',
    address: '559 ม.19 ต.เมืองเดช อ.เดชอุดม จ.อุบลราชธานี',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดขาหนีบ',
    ptDiagnosis: 'Spinal Stenosis',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 800,
    remarks: '',
    createdAt: new Date('2026-04-07T10:00:00Z').toISOString()
  },
  {
    id: 'seed-8',
    date: '2026-04-09',
    ptNo: 'PT69-008',
    serviceType: 'followup',
    citizenId: '',
    name: 'นายธีระชัย สารรักษ์',
    gender: 'male',
    birthYear: '2505',
    age: '64',
    address: 'ต.เดชอุดม อ.เดชอุดม จ.อุบลราชธานี',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ติดตามผลการประเมินปวดขาหนีบและกระดูกสันหลังทับเส้นประสาท',
    ptDiagnosis: 'Spinal Stenosis',
    treatments: ['US', 'PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-04-09T15:30:00Z').toISOString()
  },
  {
    id: 'seed-9',
    date: '2026-04-16',
    ptNo: 'PT69-009',
    serviceType: 'new',
    citizenId: '',
    name: 'นายสุทธิพร ไกรรัตน์',
    gender: 'male',
    birthYear: '2515',
    age: '54',
    address: '',
    phone: '',
    underlyingDisease: '',
    chiefComplaint: 'ปวดตึงหลัง',
    ptDiagnosis: 'LBP',
    treatments: ['PMS'],
    otherTreatment: '',
    fee: 500,
    remarks: '',
    createdAt: new Date('2026-04-16T13:45:00Z').toISOString()
  }
];

export const TREATMENT_LIST = [
  { id: 'US', label: 'US', sub: 'อัลตราซาวด์บำบัด' },
  { id: 'PMS', label: 'PMS', sub: 'กระตุ้นแม่เหล็กระงับปวด' },
  { id: 'Hot Pack', label: 'Hot Pack', sub: 'ประคบร้อน' },
  { id: 'Traction', label: 'Traction', sub: 'เครื่องดึงคอ/หลัง' },
  { id: 'Exercise', label: 'Exercise', sub: 'ออกกำลังกายบำบัด' },
  { id: 'Laser', label: 'Laser', sub: 'เลเซอร์บำบัด' },
  { id: 'ES', label: 'ES', sub: 'กระตุ้นไฟฟ้า' },
  { id: 'Manual Therapy', label: 'Manual Therapy', sub: 'ขยับดัดดึงข้อต่อ' }
];

export const PT_DIAGNOSES = [
  'MPS',
  'Frozen Shoulder',
  'OA Knee',
  'C-Spondylosis',
  'LBP',
  'Spinal Stenosis',
  'Piriformis Syndrome',
  'Herniated Disc',
  'De Quervain Tenosynovitis',
  'Plantar Fasciitis',
  'Tennis Elbow',
  'Bell\'s Palsy'
];
